### ISSUE TITLE
SQL query error when getting dataset

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/datamart-api#110]
This get command 

```
GET /datasets/ACLED-partial/variables/fatalities
```

produces this stacktrace:

```
[2020-11-17 19:40:39,961] ERROR in app: Exception on /datasets/ACLED-partial/variables/fatalities [GET]
Traceback (most recent call last):
  File "/home/ktyao/anaconda3/envs/datamart/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ktyao/anaconda3/envs/datamart/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ktyao/anaconda3/envs/datamart/lib/python3.7/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/ktyao/anaconda3/envs/datamart/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/ktyao/anaconda3/envs/datamart/lib/python3.7/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/ktyao/dev/dsbox/datamart-api/api/variable/main.py", line 11, in get
    return imp.get(dataset, variable)
  File "/home/ktyao/dev/dsbox/datamart-api/api/variable/get.py", line 79, in get
    return self.get_direct(dataset, variable, include_cols, exclude_cols, limit, regions)
  File "/home/ktyao/dev/dsbox/datamart-api/api/variable/get.py", line 126, in get_direct
    temp_cols)
  File "/home/ktyao/dev/dsbox/datamart-api/db/sql/dal/variables.py", line 321, in query_variable_data
    return query_to_dicts(query)
  File "/home/ktyao/dev/dsbox/datamart-api/db/sql/utils.py", line 55, in query_to_dicts
    cursor.execute(sql)
psycopg2.errors.DuplicateAlias: table name "e_location" specified more than once
```

The attach file contains the sql query that caused the error, kgtk edge files,  and data file:
[sql-bug.tar.gz](https://github.com/usc-isi-i2/datamart-api/files/5564473/sql-bug.tar.gz)

**Comment by kyao** [comment]
The dataset used a reserved header name for the canonical csv format. 

Need update validator to check for reserved header names. See https://github.com/usc-isi-i2/datamart-api/issues/127

Closing this issue
