### ISSUE TITLE
Error while getting retrieving data for a newly created variable

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/datamart-api#16]
Steps to reproduce,

1. Create a new variable with no qualifiers
```
test_variable = {
    "name": "test variable for test dataset",
    "variable_id": "TEST000-1"
}
```
2. Fetch data for newly created variable

```
[2020-07-08 16:47:28,052] ERROR in app: Exception on /datasets/TEST000/variables/TEST000-1 [GET]
Traceback (most recent call last):
  File "/Users/amandeep/Github/datamart-api/datamart_env/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/amandeep/Github/datamart-api/datamart_env/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/amandeep/Github/datamart-api/datamart_env/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/amandeep/Github/datamart-api/datamart_env/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/amandeep/Github/datamart-api/datamart_env/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/amandeep/Github/datamart-api/api/variable/main.py", line 11, in get
    return imp.get(dataset, variable)
  File "/Users/amandeep/Github/datamart-api/api/variable/get.py", line 87, in get
    return self.get_direct(dataset, variable, include_cols, exclude_cols, limit, regions)
  File "/Users/amandeep/Github/datamart-api/api/variable/get.py", line 188, in get_direct
    temp_cols)
  File "/Users/amandeep/Github/datamart-api/db/sql/dal/variables.py", line 289, in query_variable_data
    return query_to_dicts(query)
  File "/Users/amandeep/Github/datamart-api/db/sql/utils.py", line 55, in query_to_dicts
    cursor.execute(sql)
psycopg2.errors.SyntaxError: syntax error at or near "FROM"
LINE 8:     FROM edges AS e_main
```

This is because there are no qualifiers and the sql query formed is malformed as a result

**Comment by zmbq** [comment]
Ah, a new variable with no uploaded data. I should definitely return an indication for this. It can either be 204 NO CONTENT, or perhaps 422 Unprocessable Entry with a message saying no data has been uploaded to the variable. Yes, I think an error with an explanation is better.

**Comment by zmbq** [comment]
Fix pushed to development. A 422 error with the appropriate message is returned whenever there is no P585 qualifier associated with the variable.

**Comment by saggu** [comment]
Keeping this open until we have a proper fix

**Comment by saggu** [comment]
The API returns an empty string in this scenario, closing
