### ISSUE TITLE
psycopg2 not escaping characters properly

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/datamart-api#21]
I have 2 use cases here,

## Error while uploading data
Steps to reproduce:

1. Create a dataset - `IOM_DTM`
2. Create a variable =  `total_migrant_displaced_population`
3. Try to upload file `IOM_DTM_R10_Ethiopia_processed_ISI_displaced_population.csv` (see attached ZIP)

Error:
```
  File "/Users/amandeep/Github/datamart-api/datamart_env/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/amandeep/Github/datamart-api/datamart_env/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/amandeep/Github/datamart-api/datamart_env/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/amandeep/Github/datamart-api/datamart_env/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/amandeep/Github/datamart-api/datamart_env/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/amandeep/Github/datamart-api/api/variable/main.py", line 15, in put
    return put_data.canonical_data(dataset, variable)
  File "/Users/amandeep/Github/datamart-api/api/variable/put.py", line 364, in canonical_data
    qualifer_dict = self.get_qualifiers(variable_qnode, qualifier_labels=qualifier_columns)
  File "/Users/amandeep/Github/datamart-api/api/variable/put.py", line 273, in get_qualifiers
    qualifier_results = query_to_dicts(qualifier_query)
  File "/Users/amandeep/Github/datamart-api/db/sql/utils.py", line 55, in query_to_dicts
    cursor.execute(sql)
psycopg2.errors.SyntaxError: syntax error at or near "t"
LINE 6: ...ticks','grass (roof thatch)','brick','other','don't know','i...

```

## Error while downloading data
Steps to reproduce:

1. Create dataset - `AWSD`
2. Create variable - `total_aid_workers_affected`
3. Upload file - `AWSD_Ethiopia_processed_ISI.csv` (see attached zip)

Error: 

```
Traceback (most recent call last):
  File "/Users/amandeep/Github/datamart-api/datamart_env/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/amandeep/Github/datamart-api/datamart_env/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/amandeep/Github/datamart-api/datamart_env/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/amandeep/Github/datamart-api/datamart_env/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/amandeep/Github/datamart-api/datamart_env/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/amandeep/Github/datamart-api/api/variable/main.py", line 11, in get
    return imp.get(dataset, variable)
  File "/Users/amandeep/Github/datamart-api/api/variable/get.py", line 87, in get
    return self.get_direct(dataset, variable, include_cols, exclude_cols, limit, regions)
  File "/Users/amandeep/Github/datamart-api/api/variable/get.py", line 194, in get_direct
    temp_cols, debug=True)
  File "/Users/amandeep/Github/datamart-api/db/sql/dal/variables.py", line 289, in query_variable_data
    return query_to_dicts(query)
  File "/Users/amandeep/Github/datamart-api/db/sql/utils.py", line 55, in query_to_dicts
    cursor.execute(sql)
psycopg2.errors.SyntaxError: syntax error at or near "/"
LINE 38:   s_lngo/nrcs.text AS lngo/nrcs,
```
[Archive.zip](https://github.com/usc-isi-i2/datamart-api/files/4940831/Archive.zip)

For the second error, I will try to sanitize the input data, but the first error should be handled by `psycopg2` by escaping the `'`.

Please take a look

**Comment by zmbq** [comment]
I think we should disallow non-alphanumeric characters in qualifier names. letters, numbers and an underscore should suffice. And keep it lowercase, too. Qualifiers such as "I don't know" or "a/b" are not a good idea, and are also a huge opportunity for SQL injection. We can add a qualifier description that can contain anything the user wants, and we can return it with the metadata - for things like this.

**Comment by saggu** [comment]
Nothing to do here, I fixed this by sanitizing qualifier names
