### ISSUE TITLE
psycopg2 error DiskFull

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/datamart-api#23]
I am getting error while fetching data for a variable,

```
[2020-07-24 10:35:10,107] ERROR in app: Exception on /datasets/TEST01/variables/gender_unknown [GET]
Traceback (most recent call last):
  File "/Users/amandeep/Github/datamart-api/datamart_env/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/amandeep/Github/datamart-api/datamart_env/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/amandeep/Github/datamart-api/datamart_env/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/amandeep/Github/datamart-api/datamart_env/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/amandeep/Github/datamart-api/datamart_env/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/amandeep/Github/datamart-api/api/variable/main.py", line 11, in get
    return imp.get(dataset, variable)
  File "/Users/amandeep/Github/datamart-api/api/variable/get.py", line 87, in get
    return self.get_direct(dataset, variable, include_cols, exclude_cols, limit, regions)
  File "/Users/amandeep/Github/datamart-api/api/variable/get.py", line 194, in get_direct
    temp_cols)
  File "/Users/amandeep/Github/datamart-api/db/sql/dal/variables.py", line 289, in query_variable_data
    return query_to_dicts(query)
  File "/Users/amandeep/Github/datamart-api/db/sql/utils.py", line 55, in query_to_dicts
    cursor.execute(sql)
psycopg2.errors.DiskFull: could not resize shared memory segment "/PostgreSQL.1197549748" to 16777216 bytes: No space left on device
```

This is stopping me from testing the Annotation upload API. Any ideas how I can fix this and prevent it from happening in the future? I have seen this issue before, `docker-compose down --volumes` & `docker-compose up -d` fixed it before

**Comment by kyao** [comment]
Are you running out of disk space? Or, is this docker limit?

**Comment by saggu** [comment]
This is docker limit, I managed to fix it by changing the docker-compose, adding `shm_size`

```
services:
  db:
    image: postgres:11
    restart: always
    container_name: datamart-postgres
    shm_size: 2gb

```
