### ISSUE TITLE
Internal Server Error: Get data for a variable

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/datamart-api#4]
I have started seeing this error while getting time series data for any variable. 

Here are a couple of API calls and tracebacks,

`/datasets/UAZ/variables/VUAZ-0`
```
Traceback (most recent call last):
  File "/Users/amandeep/Github/datamart-api/datamart_env/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/amandeep/Github/datamart-api/datamart_env/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/amandeep/Github/datamart-api/datamart_env/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/amandeep/Github/datamart-api/datamart_env/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/amandeep/Github/datamart-api/datamart_env/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/amandeep/Github/datamart-api/api/variable/main.py", line 10, in get
    return imp.get(dataset, variable)
  File "/Users/amandeep/Github/datamart-api/api/variable/get.py", line 95, in get
    return self.get_direct(dataset, variable, include_cols, exclude_cols, limit, regions=regions)
  File "/Users/amandeep/Github/datamart-api/api/variable/get.py", line 183, in get_direct
    self.add_region_columns(result_df, select_cols, regions)
  File "/Users/amandeep/Github/datamart-api/api/variable/get.py", line 221, in add_region_columns
    df[col] = df['main_subject_id'].map(lambda msid: regions[msid][col]) # type: ignore
  File "/Users/amandeep/Github/datamart-api/datamart_env/lib/python3.6/site-packages/pandas/core/series.py", line 3630, in map
    new_values = super()._map_values(arg, na_action=na_action)
  File "/Users/amandeep/Github/datamart-api/datamart_env/lib/python3.6/site-packages/pandas/core/base.py", line 1145, in _map_values
    new_values = map_f(values, mapper)
  File "pandas/_libs/lib.pyx", line 2329, in pandas._libs.lib.map_infer
  File "/Users/amandeep/Github/datamart-api/api/variable/get.py", line 221, in <lambda>
    df[col] = df['main_subject_id'].map(lambda msid: regions[msid][col]) # type: ignore
KeyError: 'Q115'
```

`/datasets/OECD/variables/real_gdp_growth`
```
Traceback (most recent call last):
  File "/Users/amandeep/Github/datamart-api/datamart_env/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/amandeep/Github/datamart-api/datamart_env/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/amandeep/Github/datamart-api/datamart_env/lib/python3.6/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/amandeep/Github/datamart-api/datamart_env/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/amandeep/Github/datamart-api/datamart_env/lib/python3.6/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/amandeep/Github/datamart-api/api/variable/main.py", line 10, in get
    return imp.get(dataset, variable)
  File "/Users/amandeep/Github/datamart-api/api/variable/get.py", line 95, in get
    return self.get_direct(dataset, variable, include_cols, exclude_cols, limit, regions=regions)
  File "/Users/amandeep/Github/datamart-api/api/variable/get.py", line 183, in get_direct
    self.add_region_columns(result_df, select_cols, regions)
  File "/Users/amandeep/Github/datamart-api/api/variable/get.py", line 221, in add_region_columns
    df[col] = df['main_subject_id'].map(lambda msid: regions[msid][col]) # type: ignore
  File "/Users/amandeep/Github/datamart-api/datamart_env/lib/python3.6/site-packages/pandas/core/series.py", line 3630, in map
    new_values = super()._map_values(arg, na_action=na_action)
  File "/Users/amandeep/Github/datamart-api/datamart_env/lib/python3.6/site-packages/pandas/core/base.py", line 1145, in _map_values
    new_values = map_f(values, mapper)
  File "pandas/_libs/lib.pyx", line 2329, in pandas._libs.lib.map_infer
  File "/Users/amandeep/Github/datamart-api/api/variable/get.py", line 221, in <lambda>
    df[col] = df['main_subject_id'].map(lambda msid: regions[msid][col]) # type: ignore
KeyError: 'Q159'
```

**Comment by saggu** [comment]
Fixed
