### ISSUE TITLE
Creating a dataset with an empty URL returns a 500 error

### ISSUE THREAD

**Issue by zmbq** [usc-isi-i2/datamart-api#48]
Steps to reproduce - POST to `/metadata/datasets`

```
{
    "dataset_id": "test",
    "description": "test",
    "name": "test",
    "url": ""
}
```

A 500 error will be returned. The API's console shows the problem was detected properly in an exception that wasn't handled properly:

```
[2020-08-13 15:18:43,471] ERROR in app: Exception on /metadata/datasets [POST]  
Traceback (most recent call last):                                              
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full
                                                                                
    rv = self.dispatch_request()                                                
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in disp
                                                                                
    return self.view_functions[rule.endpoint](**req.view_args)                  
  File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 
                                                                                
    resp = resource(*args, **kwargs)                                            
  File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)                               
  File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 
                                                                                
    resp = meth(*args, **kwargs)                                                
  File "/src/api/metadata/main.py", line 157, in post                           
    edges = pd.DataFrame(metadata.to_kgtk_edges(dataset_id))                    
  File "/src/api/metadata/metadata.py", line 527, in to_kgtk_edges              
    edges.append(self.field_edge(dataset_node, 'url', required=True))           
  File "/src/api/metadata/metadata.py", line 205, in field_edge                 
    raise ValueError(f'Missing field for node {node1}: {field_name}')           
ValueError: Missing field for node Qtest: url                                   
```

**Comment by saggu** [comment]
Fixed in https://github.com/usc-isi-i2/datamart-api/commit/a31ffcac38e12f777dd64c1d65518d1f3f64eb75

Added validation for dataset creation
