### ISSUE TITLE
Error in generate t2wml code

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/datamart-api#53]
Try uploading this file to `/annotated` endpoint

[hces.xlsx.zip](https://github.com/usc-isi-i2/datamart-api/files/5105741/hces.xlsx.zip)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/src/api/annotated/main.py", line 8, in post
    return post_data.process(dataset)
  File "/src/api/annotated/post.py", line 50, in process
    t2wml_yaml_dict = to_t2wml.get_dict()
  File "/t2wml-annotation/annotation/generation/generate_t2wml.py", line 486, in get_dict
    qualifier.append(self._get_time())
  File "/t2wml-annotation/annotation/generation/generate_t2wml.py", line 365, in _get_time
    return self._get_time_multiple_formats()
  File "/t2wml-annotation/annotation/generation/generate_t2wml.py", line 288, in _get_time_multiple_formats
    spec_format = guess_year_format(self.sheet.iloc[self.data_index:, col_index])
  File "/t2wml-annotation/annotation/generation/generate_t2wml.py", line 108, in guess_year_format
    two_digit_count = values.apply(lambda x: x < 100).sum()
  File "/usr/local/lib/python3.7/site-packages/pandas/core/series.py", line 3848, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/_libs/lib.pyx", line 2329, in pandas._libs.lib.map_infer
  File "/t2wml-annotation/annotation/generation/generate_t2wml.py", line 108, in <lambda>
    two_digit_count = values.apply(lambda x: x < 100).sum()
TypeError: '<' not supported between instances of 'str' and 'int'
```

**Comment by kyao** [comment]
Fixed
